version: "3.8"
services:
  ts-sample:
    container_name: ts-sample
    command: npm run start
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    ports:
      - 8080:8080
    stdin_open: true

volumes:
    nodemodules:
